version: '3.5'

services:
  elk:
    build: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - "./elk-data:/var/lib/elasticsearch"

  jupyter:
    build: jupyter
    ports:
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - "./notebook:/home/jovyan/work"
